---
- name: Create HAProxy config from template
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  when: inventory_hostname == "lb"

- name: Reload HAproxy
  systemd:
    name: haproxy
    state: reloaded
  when: inventory_hostname == "lb"

- name: Ensure all backends in HAProxy are enabled
  haproxy:
    state: enabled
    socket: /run/haproxy/admin.sock
    host: "{{item}}"
    backend: web
    fail_on_not_found: yes
  with_list: "{{groups.apps}}"
  when: inventory_hostname == "lb"

- name: Ensure enpoint is responsive - Fail task if not
  include_tasks: tests.yml
  with_sequence: count="{{groups.apps|length}}"
  when: inventory_hostname == "lb"