---
- hosts: app*
  roles:
    - role: nginxinc.nginx
      vars:
        http_template_enable: true
        main_template_enable: true
        http_push_enable: true
        # Set http_template_server_name var to "empty" due to default template using localhost server_name
        http_template_server_name: "empty"
    - role: geerlingguy.php
      vars:
        php_date_timezone: "Europe/London"
        php_webserver_daemon: nginx
        php_enable_php_fpm: true
        php_fpm_pool_user: www-data
        php_fpm_pool_group: www-data
    - role: geerlingguy.composer
    - role: app