---
- hosts: all
  roles:
    - role: entercloudsuite.haproxy
      haproxy_user: haproxyuser
      haproxy_pass: haproxypass
      tags: haproxy_install
      
    - role: haproxy
      tags: haproxy_configure